### PR TITLE
Add PostgreSQL template

### PR DESCRIPTION
**Pull request by cvarjao**
- Add PostgreSQL template
- Update template to use `gluster-file-db`

### CODE REVIEW

**Comment by sheaphillips** [comment]
We had talked at one point about "forking" the templates and maintaining 'bcgov' versions of the OOTB templates containing our (hopefully minor) cutomizations plus some metadata that would identify the templates as "customized for BC Gov" as well as possibly "endorsed".  We did that with the Jenkins template.  In that case, there is a specific dependency to do with OpenShift Pipelines as well, but most won't have this.

**Comment by sheaphillips** [comment]
Didn't quite finish my thoughts above...In short I think we should probably leave the OOTB templates "as-is"  and create our own based on them, with whatever customizations we need, plus bc gov metadata.  In parallel we can start "curating" (disabling) OOTB templates that we don't want, so the non-customized ones don't show up. Make sense?

**Comment by cvarjao** [comment]
@sheaphillips, write. I was thinking the move from `openshift` to `bcgov` namespaces to be done in 2 phase. First, identifying the customized templates, and document here, and then we can move them to a new namespace. So, this is the first customized template I would be bringing to this repository. And yes, there are components that requires more than a template, but also building images.

**Comment by sheaphillips** [comment]
cool. as long as the "customized" template ends up added to the namespace
with metadata to show that it's "bcgov" and customizations are tracked via
git then that's cool.

**Pull request merged**
