### PR TITLE
Add node 10 cicd image

### PR DESCRIPTION
**Pull request by jleach**
Node 10 has reached LTS and people are starting to use it; it's a requirement for the latest `create-react-app` scripts. This PR creates a new builder image so that updated ReactJS apps can build.

### CODE REVIEW

**Comment by jleach** [comment]
@sheaphillips @cvarjao Are you guys able to add this image to the catalogue; anyone who's updated to the latest ReactJS will need to use node 10 to do a build. I'm doing it because Range needs it. Thx.

**Comment by cvarjao** [comment]
@jleach, I wonder if we should continue to support/endorse having specific Jenkins slave images. I think the build should run within the nodejs container itself as it may also be a runtime requirement.

RedHat have now Node 10 in their catalogue: https://access.redhat.com/containers/#/registry.access.redhat.com/rhoar-nodejs/nodejs-10

**Comment by jleach** [comment]
@cvarjao I'm find with that. I thought the slave images had some Jenkins stuff in them to allow them to work as a slave; they're all based of `jenkins-slave-base-rhel7` as a base image. What's thew process for using the runtime? Just source as the image?

**Comment by cvarjao** [comment]
@jleach , for range specifically, can't it just run all as part of the build/assemble:
- npm ci
- npm run build
- npx nsp check
- npm run test:ci

If any of that fails, the build is considered failed. The tricky part may be getting the coverage reports to feed to sonarqube. It just means running the pod with a dumb entry-point and getting the reports (maybe via `oc rsync`) before running sonarqube scanner.

Depending on what is require, you may also use `postCommit` for validations: `oc explain bc.spec.postCommit`

**Comment by cvarjao** [comment]
@jleach , can you please rename `cicd/nodejs10` to `cicd/jenkins-slave-nodejs-10`. I will be renaming the other ones to match.

**Comment by jleach** [comment]
@cvarjao Done.

**Pull request merged**
